name: lint_staged
description:
  Run linters on git staged files for your Flutter and Dart projects.
version: 0.2.0
homepage: https://github.com/hyiso/lint_staged
repository: https://github.com/hyiso/lint_staged

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansi: ^0.2.2
  ansi_escapes: ^1.1.0
  ansi_slice: ^0.1.1
  ansi_strip: ^0.1.1+1
  ansi_wrap: ^0.1.2+1
  args: ^2.3.1
  glob: ^2.0.1
  path: ^1.8.0
  verbose: ^0.1.0
  yaml: ^3.1.1

dev_dependencies:
  commitlint_cli: ^0.4.0-pre.0
  husky: ^0.1.6
  lints: ^2.0.0
  test: ^1.16.0

lint_staged:
  '**.dart': dart fix --apply && dart format --fix