name: lint_staged
description:
  Run linters on git staged files for your Flutter and Dart projects.
version: 0.4.3
homepage: https://github.com/hyiso/lint_staged
repository: https://github.com/hyiso/lint_staged

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ansi: ^0.4.0
  ansi_escapes: ^1.1.0
  args: ^2.3.1
  glob: ^2.0.1
  path: ^1.8.0
  verbose: ^0.1.0
  yaml: ^3.1.1

dev_dependencies:
  husky: ^0.1.6
  lints: ^2.0.0
  test: ^1.16.0

lint_staged:
  '*/**.dart': dart fix --apply && dart format --fix